apiVersion: v1
kind: ConfigMap
metadata:
  name: basketapi-config
data:
  DB_HOST: redis-service
  DB_PORT: "6379"
  RABBITMQ_HOST: rabbitmq-service
  RABBITMQ_PORT: "15672"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redisdb
          image: redis:alpine
          ports:
            - containerPort: 6379
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi-pod
  template:
    metadata:
      labels:
        app: basketapi-pod
    spec:
      containers:
        - name: basketapi
          image: caiotmello/basketapi:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: basketapi-config
            - secretRef:
                name: rabbitmq-secret

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-pod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  selector:
    app: basketapi-pod
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8889
      targetPort: 8081
  type: LoadBalancer
