name: Build and Deploy Application to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdin
        
      - name: Basket Api - Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Services/Basket/Basket.API/Dockerfile
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USER}}/basketapi:v${{ github.run_number }}
            ${{secrets.DOCKERHUB_USER}}/basketapi:latest
            
      - name: Ordering Api - Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Services/Ordering/Ordering.API/Dockerfile
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USER}}/orderingapi:v${{ github.run_number }}
            ${{secrets.DOCKERHUB_USER}}/ordering:latest
