name: Build and Deploy Application to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo saopaulo160994 | docker login -u caiotmello --password-stdin

      - name: teste 
        run: echo pwd | echo ls
        
      - name: Basket Api - Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src/Services/Basket/Basket.API
          file: ./src/Services/Basket/Basket.API/Dockerfile
          push: true
          tags: |
            caiotmello/basketapi:v${{ github.run_number }}
            caiotmello/basketapi:latest
            
      - name: Ordering Api - Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src//Services/Ordering/Ordering.API
          file: ./src//Services/Ordering/Ordering.API/Dockerfile
          push: true
          tags: |
            caiotmello/orderingapi:v${{ github.run_number }}
            caiotmello/ordering:latest
